<a href="https://colab.research.google.com/github/25pa1a45a0-cmyk/NASSCOM/blob/main/Copy_of_Pandas_Lab_1_Introduction_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas Lab 1 — Introduction to Pandas & DataFrames



**Objective:** Learn the basics of Pandas and work with structured/tabular data using `Series` and `DataFrame`.

### What you will learn
- Why Pandas is used in Data Science and Machine Learning
- Importing Pandas
- Creating a Series
- Creating a DataFrame
- Reading a CSV file
- Inspecting a dataset using `head()`, `tail()`, `shape`, `columns`, `dtypes`, `info()` and `describe()`
- Selecting columns from a DataFrame

### Running example
We will use a **Student Performance dataset**, which connects this lab with the supervised-learning concept discussed in class.

## 1. Why Pandas?

In Machine Learning, data often comes in a table such as a CSV or Excel file.

For example:

| Student | Study_Hours | Attendance | Assignments | Previous_Marks | Final_Result |
|---|---:|---:|---:|---:|---|
| S1 | 1 | 55 | 2 | 38 | Fail |
| S2 | 2 | 60 | 3 | 42 | Fail |
| S3 | 3 | 72 | 6 | 52 | Pass |
| S4 | 5 | 82 | 8 | 64 | Pass |

**Pandas** is a Python library designed for working with structured/tabular data.

A simple way to remember:

**NumPy → numerical arrays and numerical computation**  
**Pandas → tables, columns, rows and data analysis**

##pip instal pandas

In [2]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 2.2.3

## 2. Pandas Series

A **Series** represents a one-dimensional labelled sequence of data.

Think of it as **one column** of a table.

In [ ]:
marks = pd.Series([65, 72, 81, 55, 90])
marks

0    65
1    72
2    81
3    55
4    90
dtype: int64

### Observe the index

Pandas automatically gives each value an index starting from 0.

In [ ]:
print("Second value:", marks[1])
print("Fourth value:", marks[3])

Second value: 72
Fourth value: 55

### Exercise 1 ✏️
Create a Pandas Series containing the marks of 6 students and print the third student's mark.

In [4]:
import pandas as pd
marks=pd.array([56,85,74,65,92,43])
print("Third student marks:",marks[2])

Third student marks: 74

## 3. Pandas DataFrame

A **DataFrame** is a two-dimensional labelled data structure.

You can think of it as a **table containing rows and columns**.

In [11]:
data = {
    "Name": ["Anu", "Bharath", "Charan"],
    "Marks": [65, 72, 81],
    "Attendance": [80, 75, 90]
}

s=pd.DataFrame(data)
print(s)

      Name  Marks  Attendance
0      Anu     65          80
1  Bharath     72          75
2   Charan     81          90

### Series vs DataFrame

- **Series → one-dimensional → think one column**
- **DataFrame → two-dimensional → think complete table**

## 4. Create the Student Performance DataFrame

We will now use a dataset similar to the one discussed in the supervised-learning class.

In [13]:
student_data = {
    "Student": ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10",
                "S11", "S12", "S13", "S14", "S15", "S16", "S17", "S18", "S19", "S20"],
    "Study_Hours": [1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 1, 2, 4, 6],
    "Attendance": [55, 60, 65, 68, 72, 70, 75, 78, 82, 80, 85, 88, 90, 86, 92, 90, 50, 58, 62, 75],
    "Assignments": [2, 3, 4, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 10, 10, 1, 2, 5, 8],
    "Previous_Marks": [38, 42, 45, 48, 52, 55, 58, 61, 64, 66, 70, 73, 76, 78, 82, 85, 35, 40, 50, 68],
    "Final_Result": ["Fail", "Fail", "Fail", "Fail", "Pass", "Pass", "Pass", "Pass", "Pass", "Pass",
                     "Pass", "Pass", "Pass", "Pass", "Pass", "Pass", "Fail", "Fail", "Fail", "Pass"]
}

students = pd.DataFrame(student_data)

students

   Student  Study_Hours  Attendance  Assignments  Previous_Marks Final_Result
0       S1            1          55            2              38         Fail
1       S2            2          60            3              42         Fail
2       S3            2          65            4              45         Fail
3       S4            3          68            5              48         Fail
4       S5            3          72            6              52         Pass
5       S6            4          70            6              55         Pass
6       S7            4          75            7              58         Pass
7       S8            5          78            7              61         Pass
8       S9            5          82            8              64         Pass
9      S10            6          80            8              66         Pass
10     S11            6          85            9              70         Pass
11     S12            7          88            9              73         Pass
12     S13            7          90           10              76         Pass
13     S14            8          86           10              78         Pass
14     S15            8          92           10              82         Pass
15     S16            9          90           10              85         Pass
16     S17            1          50            1              35         Fail
17     S18            2          58            2              40         Fail
18     S19            4          62            5              50         Fail
19     S20            6          75            8              68         Pass

## 5. Save the Dataset as a CSV File

In real projects, data is often received as a CSV file. Let's create one from our DataFrame so that we can practice reading it.

In [17]:
students.to_csv("students.csv", index=False)
print("students.csv created successfully")

students.csv created successfully

## 6. Read a CSV File using Pandas

The most common syntax is:

```python
pd.read_csv("filename.csv")
```

This reads the CSV file and creates a DataFrame.

In [18]:
df = pd.read_csv("students.csv")
df

   Student  Study_Hours  Attendance  Assignments  Previous_Marks Final_Result
0       S1            1          55            2              38         Fail
1       S2            2          60            3              42         Fail
2       S3            2          65            4              45         Fail
3       S4            3          68            5              48         Fail
4       S5            3          72            6              52         Pass
5       S6            4          70            6              55         Pass
6       S7            4          75            7              58         Pass
7       S8            5          78            7              61         Pass
8       S9            5          82            8              64         Pass
9      S10            6          80            8              66         Pass
10     S11            6          85            9              70         Pass
11     S12            7          88            9              73         Pass
12     S13            7          90           10              76         Pass
13     S14            8          86           10              78         Pass
14     S15            8          92           10              82         Pass
15     S16            9          90           10              85         Pass
16     S17            1          50            1              35         Fail
17     S18            2          58            2              40         Fail
18     S19            4          62            5              50         Fail
19     S20            6          75            8              68         Pass

## 7. `head()` — View the First Rows

By default, `head()` displays the first 5 rows.

In [19]:
df.head(10)

  Student  Study_Hours  Attendance  Assignments  Previous_Marks Final_Result
0      S1            1          55            2              38         Fail
1      S2            2          60            3              42         Fail
2      S3            2          65            4              45         Fail
3      S4            3          68            5              48         Fail
4      S5            3          72            6              52         Pass
5      S6            4          70            6              55         Pass
6      S7            4          75            7              58         Pass
7      S8            5          78            7              61         Pass
8      S9            5          82            8              64         Pass
9     S10            6          80            8              66         Pass

You can also specify the number of rows:

In [20]:
df.head(3)

  Student  Study_Hours  Attendance  Assignments  Previous_Marks Final_Result
0      S1            1          55            2              38         Fail
1      S2            2          60            3              42         Fail
2      S3            2          65            4              45         Fail

## 8. `tail()` — View the Last Rows

In [21]:
df.tail()

   Student  Study_Hours  Attendance  Assignments  Previous_Marks Final_Result
15     S16            9          90           10              85         Pass
16     S17            1          50            1              35         Fail
17     S18            2          58            2              40         Fail
18     S19            4          62            5              50         Fail
19     S20            6          75            8              68         Pass

## 9. `shape` — Number of Rows and Columns

`shape` returns:

```text
(number_of_rows, number_of_columns)
```

In [22]:
print(df.shape)

(20, 6)

### Exercise 2 ✏️
Use `shape` to find how many rows and columns are present in the student dataset.

In [23]:
students.shape

(20, 6)

## 10. `columns` — View Column Names

In [24]:
df.columns

Index(['Student', 'Study_Hours', 'Attendance', 'Assignments', 'Previous_Marks',
       'Final_Result'],
      dtype='object')

You can also convert the column names into a Python list:

In [ ]:
df.columns.tolist()

['Student',
 'Study_Hours',
 'Attendance',
 'Assignments',
 'Previous_Marks',
 'Final_Result']

## 11. `dtypes` — Data Type of Each Column

In [25]:
df.dtypes

Student           object
Study_Hours        int64
Attendance         int64
Assignments        int64
Previous_Marks     int64
Final_Result      object
dtype: object

Observe that numerical columns and text/categorical columns have different data types.

**Question:** What data type do you see for `Study_Hours`? What about `Final_Result`?

## 12. `info()` — Quick Dataset Information

`info()` is one of the most useful commands when we first receive a dataset.

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student         20 non-null     object
 1   Study_Hours     20 non-null     int64
 2   Attendance      20 non-null     int64
 3   Assignments     20 non-null     int64
 4   Previous_Marks  20 non-null     int64
 5   Final_Result    20 non-null     object
dtypes: int64(4), object(2)
memory usage: 1.1+ KB

`info()` helps us inspect:

- number of rows
- column names
- non-null values
- data types

This is part of **understanding the dataset** before machine learning.

## 13. `describe()` — Statistical Summary

`describe()` gives statistical information for numerical columns.

In [27]:
df.describe()

       Study_Hours  Attendance  Assignments  Previous_Marks
count    20.000000   20.000000    20.000000       20.000000
mean      4.650000   74.050000     6.500000       59.300000
std       2.433862   12.742284     2.928984       15.321468
min       1.000000   50.000000     1.000000       35.000000
25%       2.750000   64.250000     4.750000       47.250000
50%       4.500000   75.000000     7.000000       59.500000
75%       6.250000   85.250000     9.000000       70.750000
max       9.000000   92.000000    10.000000       85.000000

Look at the values for:

- count
- mean
- std
- min
- 25%
- 50%
- 75%
- max

We will study these statistics in more detail during EDA.

## 14. Selecting One Column

Use:

```python
df["column_name"]
```

In [28]:
df["Study_Hours"]

0     1
1     2
2     2
3     3
4     3
5     4
6     4
7     5
8     5
9     6
10    6
11    7
12    7
13    8
14    8
15    9
16    1
17    2
18    4
19    6
Name: Study_Hours, dtype: int64

Notice that selecting one column returns a **Series**.

## 15. Selecting Multiple Columns

Use a list of column names inside the brackets.

In [29]:
df[["Study_Hours", "Attendance"]]

    Study_Hours  Attendance
0             1          55
1             2          60
2             2          65
3             3          68
4             3          72
5             4          70
6             4          75
7             5          78
8             5          82
9             6          80
10            6          85
11            7          88
12            7          90
13            8          86
14            8          92
15            9          90
16            1          50
17            2          58
18            4          62
19            6          75

This returns a **DataFrame** because we selected multiple columns.

## 16. Selecting Useful Student Information

Let's select the columns that could be useful for understanding student performance.

In [30]:
df[["Student", "Study_Hours", "Previous_Marks", "Final_Result"]]

   Student  Study_Hours  Previous_Marks Final_Result
0       S1            1              38         Fail
1       S2            2              42         Fail
2       S3            2              45         Fail
3       S4            3              48         Fail
4       S5            3              52         Pass
5       S6            4              55         Pass
6       S7            4              58         Pass
7       S8            5              61         Pass
8       S9            5              64         Pass
9      S10            6              66         Pass
10     S11            6              70         Pass
11     S12            7              73         Pass
12     S13            7              76         Pass
13     S14            8              78         Pass
14     S15            8              82         Pass
15     S16            9              85         Pass
16     S17            1              35         Fail
17     S18            2              40         Fail
18     S19            4              50         Fail
19     S20            6              68         Pass

## 🧠 Mini Practice Set

Try these without looking at the previous cells.

### Question 1
Display only the `Attendance` column.

### Question 2
Display `Student` and `Final_Result`.

### Question 3
Display the first 10 rows.

### Question 4
Find the number of rows and columns.

### Question 5
Display the data types of all columns.

In [38]:
# Q1
df["Attendance"]


# Q2
df[["Student","Final_Result"]]


# Q3
df.head(10)


# Q4
df.shape


# Q5
df.dtypes

Student           object
Study_Hours        int64
Attendance         int64
Assignments        int64
Previous_Marks     int64
Final_Result      object
dtype: object

## 🎯 Lab Challenge

Without changing the original dataset, answer these questions using Pandas:

1. How many students are present in the dataset?
2. How many features/columns are present?
3. What are the column names?
4. Display the first 7 students.
5. Display the last 4 students.
6. Display only `Study_Hours` and `Final_Result`.
7. Display `Attendance`, `Previous_Marks`, and `Final_Result`.
8. Display the statistical summary of the numerical columns.
9. Check the data types of all columns.
10. Display the complete information about the dataset using `info()`.

1.There are 20 Students

2.There are 6 columns or features

3.The column names are:Student,Study_Hours,Attendance,Previous_Marks,Assignments,Final_Result

In [39]:
df.head(7) ## first 10 students

  Student  Study_Hours  Attendance  Assignments  Previous_Marks Final_Result
0      S1            1          55            2              38         Fail
1      S2            2          60            3              42         Fail
2      S3            2          65            4              45         Fail
3      S4            3          68            5              48         Fail
4      S5            3          72            6              52         Pass
5      S6            4          70            6              55         Pass
6      S7            4          75            7              58         Pass

In [40]:
df.tail(4) ##last 4 students

   Student  Study_Hours  Attendance  Assignments  Previous_Marks Final_Result
16     S17            1          50            1              35         Fail
17     S18            2          58            2              40         Fail
18     S19            4          62            5              50         Fail
19     S20            6          75            8              68         Pass

In [42]:
df[["Study_Hours","Final_Result"]] ##only studyhours and finalresult

    Study_Hours Final_Result
0             1         Fail
1             2         Fail
2             2         Fail
3             3         Fail
4             3         Pass
5             4         Pass
6             4         Pass
7             5         Pass
8             5         Pass
9             6         Pass
10            6         Pass
11            7         Pass
12            7         Pass
13            8         Pass
14            8         Pass
15            9         Pass
16            1         Fail
17            2         Fail
18            4         Fail
19            6         Pass

In [43]:
df[["Attendance","Previous_Marks","Final_Result"]] ##attendance,previousmarks and finalresult

    Attendance  Previous_Marks Final_Result
0           55              38         Fail
1           60              42         Fail
2           65              45         Fail
3           68              48         Fail
4           72              52         Pass
5           70              55         Pass
6           75              58         Pass
7           78              61         Pass
8           82              64         Pass
9           80              66         Pass
10          85              70         Pass
11          88              73         Pass
12          90              76         Pass
13          86              78         Pass
14          92              82         Pass
15          90              85         Pass
16          50              35         Fail
17          58              40         Fail
18          62              50         Fail
19          75              68         Pass

In [44]:
df.describe() ##describe summary of numerical columns

       Study_Hours  Attendance  Assignments  Previous_Marks
count    20.000000   20.000000    20.000000       20.000000
mean      4.650000   74.050000     6.500000       59.300000
std       2.433862   12.742284     2.928984       15.321468
min       1.000000   50.000000     1.000000       35.000000
25%       2.750000   64.250000     4.750000       47.250000
50%       4.500000   75.000000     7.000000       59.500000
75%       6.250000   85.250000     9.000000       70.750000
max       9.000000   92.000000    10.000000       85.000000

In [45]:
df.dtypes ##data type of each column

Student           object
Study_Hours        int64
Attendance         int64
Assignments        int64
Previous_Marks     int64
Final_Result      object
dtype: object

In [46]:
df.info() ##complete information about the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student         20 non-null     object
 1   Study_Hours     20 non-null     int64
 2   Attendance      20 non-null     int64
 3   Assignments     20 non-null     int64
 4   Previous_Marks  20 non-null     int64
 5   Final_Result    20 non-null     object
dtypes: int64(4), object(2)
memory usage: 1.1+ KB

## 🔗 Connection to Machine Learning

In the supervised-learning example, we identified:

- **Features:** Study_Hours, Attendance, Assignments, Previous_Marks
- **Target:** Final_Result

Pandas helps us work with this dataset before we give the data to an ML algorithm.

### Remember the workflow

```text
CSV Dataset
    ↓
Pandas DataFrame
    ↓
Understand the Data
    ↓
Clean / Transform
    ↓
EDA
    ↓
Preprocessing
    ↓
Machine Learning Model
```

## ✅ Lab 1 Recap

Today we learned:

✔ Import Pandas  
✔ Series  
✔ DataFrame  
✔ Create a DataFrame  
✔ Read a CSV file  
✔ `head()` and `tail()`  
✔ `shape`  
✔ `columns`  
✔ `dtypes`  
✔ `info()`  
✔ `describe()`  
✔ Select one or multiple columns  

### Next Lab
**Pandas Lab 2 — Selecting, Filtering, Sorting, Statistics and GroupBy**